# Generated by Django 3.2.4 on 2021-06-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('licence_number', models.CharField(max_length=100, unique=True)),
                ('current_ranking', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField()),
                ('number_of_ranked_players', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SponsorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('tournament', models.ManyToManyField(to='project.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('winner1', models.CharField(max_length=100, null=True)),
                ('winner2', models.CharField(max_length=100, null=True)),
                ('applicant1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant1', to='project.applicant')),
                ('applicant2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant2', to='project.applicant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='tournament',
            field=models.ManyToManyField(to='project.Tournament'),
        ),
    ]
